services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SHUFTI_CLIENT_ID=${SHUFTI_CLIENT_ID}
      - SHUFTI_SECRET_KEY=${SHUFTI_SECRET_KEY}
      - DATABASE_URL=file:./dev.db
    volumes:
      # Mount database volume for persistence
      - ./prisma:/app/prisma
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
