services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "3003:3000"
    env_file:
      - .env
      - .env.docker
    volumes:
      # Use named volume for SQLite database persistence
      - sqlite-data:/app/data
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

volumes:
  sqlite-data:
    driver: local
